### ISSUE TITLE
KSServicePocketsphinx can't be instantiated

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/smarthome#37]
Without installing Pocketsphinx by-hand all `KSServicePocketsphinx` tests fail as `KSServicePocketsphinx` is unable to be instantiated. The test log is full with errors of the form

```
!ENTRY org.eclipse.equinox.ds 4 0 2016-04-17 13:41:34.986
!MESSAGE Exception occurred while creating new instance of component Component[
        name = org.eclipse.smarthome.io.voice.ksservice
        activate = activate
        deactivate = deactivate
        modified =
        configuration-policy = optional
        factory = null
        autoenable = true
        immediate = true
        implementation = org.eclipse.smarthome.io.voice.internal.KSServicePocketsphinx
        state = Unsatisfied
        properties = {os=any}
        serviceFactory = false
        serviceInterface = [org.eclipse.smarthome.io.voice.KSService]
        references = null
        located in bundle = org.eclipse.smarthome.io.voice_0.8.0.201604171136 [84]
]
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.smarthome.io.voice.internal.KSServicePocketsphinx
        at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.createInstance(ServiceComponent.java:493)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.createInstance(ServiceComponentProp.java:270)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:331)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:458)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.setProperties(ServiceRegistrationImpl.java:168)
        at org.eclipse.equinox.internal.app.EclipseAppDescriptor.refreshProperties(EclipseAppDescriptor.java:124)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.refreshAppDescriptors(EclipseAppContainer.java:470)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.unlock(EclipseAppContainer.java:540)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.setAppStatus(EclipseAppHandle.java:162)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.setInternalResult(EclipseAppHandle.java:230)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:202)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

@andrenatal can you take a look at this? My guess is that all the lib paths are incorrect and you didn't notice as you have pocketsphinx installed in the standard location.

**Comment by andrenatal** [comment]
Thanks, yes. I have a couple of questions: what platform were you compiling? OSX or Linux? It was a fresh build in a fresh box or in your developer one? If Linux and fresh install, could you share how you overcome the issue with "org.eclipse.smarthome.model.item" that hit everybody?  @tilmankamp   travis, and also @nhirata  and mine local builds)

**Comment by kdavis-mozilla** [comment]
It's a fresh Ubuntu 14.04 box. The "org.eclipse.smarthome.model.item" issue was overcome by copying the apropos bundles, in src form, from my laptop The "org.eclipse.smarthome.model.item" arises as the xtext generation in the generate-source phase doesn't run w/maven. I'm not sure why this happens, but it does.

**Comment by kdavis-mozilla** [comment]
However, you should note the "org.eclipse.smarthome.model.item" issue and this issue are **different issues** and the "org.eclipse.smarthome.model.item" issue **does not block** work on this issue.

**Comment by andrenatal** [comment]
This was fixed in this [commit](https://github.com/mozilla/pocketsphinx/commit/dfd034367e847d5c224b31ee768a0385bd457a41)
